jobs:
  contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/prepare
      - uses: JoshuaKGoldberg/all-contributors-auto-action@v0.0.3
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Fill in all-contributors"

name: Contributors

on:
  push:
    branches:
      - main
